let items=[];
let activeCategory="";
const $=selector=>document.querySelector(selector);
const menuButton=$(".menu-button");
const navigation=$(".main-nav");
if(menuButton&&navigation){menuButton.addEventListener("click",()=>{const open=navigation.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});navigation.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{navigation.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}))}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]))}
function imageFor(item){return item.thumbnail||item.image}
function displayCategory(name){return name==="Tshirts"?"T-Shirts & Art":name}
function categoryOrder(categories){const preferred=["Birds","Butterflies","Flowers","Sunsets","Insects","Landscapes","Mammals","Orchids","Tshirts"];return [...categories].sort((a,b)=>{const ai=preferred.indexOf(a),bi=preferred.indexOf(b);return (ai<0?99:ai)-(bi<0?99:bi)||a.localeCompare(b)})}
function groupedItems(){return items.reduce((map,item)=>{(map[item.category]??=[]).push(item);return map},{})}
function renderCategories(){const groups=groupedItems();const categories=categoryOrder(Object.keys(groups));const grid=$("#categoryGrid");grid.innerHTML=categories.map(category=>{const group=groups[category];const cover=group.find(i=>i.thumbnail)||group[0];return `<button class="category-card" data-category="${escapeHtml(category)}"><img src="${escapeHtml(imageFor(cover))}" alt="${escapeHtml(displayCategory(category))}" loading="lazy"><span class="category-shade"></span><span class="category-copy"><h3>${escapeHtml(displayCategory(category))}</h3><p>${group.length} ${group.length===1?"image":"images"}</p></span><span class="category-arrow">→</span></button>`}).join("");grid.querySelectorAll(".category-card").forEach(card=>card.addEventListener("click",()=>openGallery(card.dataset.category)))}
function renderFeatured(){const groups=groupedItems();const categories=categoryOrder(Object.keys(groups));const picks=categories.slice(0,8).map((category,index)=>{const group=groups[category];return group[index%group.length]});const grid=$("#featuredGrid");grid.innerHTML=picks.map(item=>`<article class="featured-card" data-index="${items.indexOf(item)}"><img src="${escapeHtml(imageFor(item))}" alt="${escapeHtml(item.alt||displayCategory(item.category))}" loading="lazy"><span class="featured-badge">${escapeHtml(displayCategory(item.category))}</span></article>`).join("");grid.querySelectorAll(".featured-card").forEach(card=>card.addEventListener("click",()=>openModal(items[Number(card.dataset.index)])))}
function openGallery(category){activeCategory=category;$("#galleryTitle").textContent=displayCategory(category);$("#searchBox").value="";renderPortfolio();const panel=$("#galleryPanel");panel.classList.add("open");panel.setAttribute("aria-hidden","false");document.body.classList.add("no-scroll");panel.scrollTop=0}
function closeGallery(){const panel=$("#galleryPanel");panel.classList.remove("open");panel.setAttribute("aria-hidden","true");document.body.classList.remove("no-scroll")}
function renderPortfolio(){const search=$("#searchBox").value.trim().toLowerCase();const filtered=items.filter(item=>item.category===activeCategory).filter(item=>`${item.title||""} ${item.description||""} ${(item.keywords||[]).join(" ")} ${item.location||""}`.toLowerCase().includes(search));$("#galleryCount").textContent=`${filtered.length} ${filtered.length===1?"image":"images"}`;const grid=$("#portfolioGrid");grid.innerHTML=filtered.length?filtered.map(item=>`<article class="portfolio-card" data-index="${items.indexOf(item)}"><img src="${escapeHtml(imageFor(item))}" alt="${escapeHtml(item.alt||displayCategory(item.category))}" loading="lazy"><span class="portfolio-overlay"></span><span class="portfolio-meta">View image →</span></article>`).join(""):`<p class="empty-state">No images matched your search.</p>`;grid.querySelectorAll(".portfolio-card").forEach(card=>card.addEventListener("click",()=>openModal(items[Number(card.dataset.index)])))}
const modal=$("#imageModal");
function cleanTitle(item){const title=String(item.title||"").trim();if(!title||/^(bee|bird|card|img|image|photo|sunset|flower|butterfly)[\s_\-]*(\(?\d+\)?)?$/i.test(title))return "";return title}
function openModal(item){$("#modalImage").src=item.image;$("#modalImage").alt=item.alt||displayCategory(item.category);$("#modalCategory").textContent=`${displayCategory(item.category)} • ${item.store||"KK Florida"}`;const title=cleanTitle(item);$("#modalTitle").textContent=title;$("#modalTitle").classList.toggle("visually-hidden-title",!title);const description=item.description||`Original ${displayCategory(item.category).toLowerCase()} photography and artwork from KK Florida.`;$("#modalDescription").textContent=description;const link=$("#modalLink");link.href=item.link||item.purchaseUrl||"#";link.textContent=item.store==="TeePublic"?"View this design on TeePublic":"Shop this photo on Picfair";modal.classList.add("open");modal.setAttribute("aria-hidden","false")}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}
$("#galleryClose").addEventListener("click",closeGallery);$("#searchBox").addEventListener("input",renderPortfolio);$("#modalClose").addEventListener("click",closeModal);modal.addEventListener("click",event=>{if(event.target===modal)closeModal()});document.addEventListener("keydown",event=>{if(event.key==="Escape"){if(modal.classList.contains("open"))closeModal();else if($("#galleryPanel").classList.contains("open"))closeGallery()}});
fetch("data/gallery.json").then(response=>response.json()).then(data=>{items=Array.isArray(data)?data:(data.items||[]);renderCategories();renderFeatured()}).catch(error=>{$("#categoryGrid").innerHTML="<p>The gallery could not be loaded.</p>";console.error(error)});
fetch("data/hero.json").then(r=>r.json()).then(slides=>{const host=$("#heroSlides");host.innerHTML=slides.map((s,i)=>`<div class="hero-slide ${i===0?"active":""}" style="background-image:url('${s.image}')" role="img" aria-label="${escapeHtml(s.alt)}"></div>`).join("");const els=[...host.children];if(els.length>1){let index=0;setInterval(()=>{els[index].classList.remove("active");index=(index+1)%els.length;els[index].classList.add("active")},6500)}});
