let guides=[],gallery=[],activeFilter="All";
const $=s=>document.querySelector(s);
const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const menuButton=$(".menu-button"),navigation=$(".main-nav");if(menuButton&&navigation){menuButton.addEventListener("click",()=>{const open=navigation.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))})}
function relatedImage(guide){const map={"Birds":["Birds"],"Butterflies":["Butterflies"],"Dragonflies":["Dragonflies","Insects"],"Everglades Wildlife":["Reptiles","Mammals","Everglades","Birds"],"Florida Plants":["Flowers","Plants","Orchids","Trees"],"Photography Tips":["Landscapes","Birds","Butterflies","Sunsets"]};const cats=map[guide.category]||[];const pool=gallery.filter(i=>cats.includes(i.category));if(!pool.length)return "";let hash=[...guide.title].reduce((a,c)=>a+c.charCodeAt(0),0);const item=pool[hash%pool.length];return item.thumbnail||item.image||""}
function categories(){return ["All",...new Set(guides.map(g=>g.category))]}
function renderFilters(){const host=$("#guideFilters");host.innerHTML=categories().map(c=>`<button class="guide-filter ${c===activeFilter?"active":""}" data-filter="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join("");host.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;renderFilters();renderGuides()}))}
function renderGuides(){const q=$("#guideSearch").value.trim().toLowerCase();const filtered=guides.filter(g=>activeFilter==="All"||g.category===activeFilter).filter(g=>Object.values(g).join(" ").toLowerCase().includes(q));$("#guideCount").textContent=`${filtered.length} ${filtered.length===1?"guide":"guides"}`;$("#guideGrid").innerHTML=filtered.length?filtered.map(g=>{const img=relatedImage(g);return `<article class="wildlife-guide-card" data-slug="${g.slug}"><div class="guide-card-image" ${img?`style="background-image:url('${escapeHtml(img)}')"`:""}><span>${escapeHtml(g.category)}</span></div><div class="guide-card-copy"><h3>${escapeHtml(g.title)}</h3>${g.scientific?`<p class="scientific-name">${escapeHtml(g.scientific)}</p>`:""}<p>${escapeHtml(g.summary)}</p><button>Read guide →</button></div></article>`}).join(""):`<p class="empty-state">No guides matched your search.</p>`;document.querySelectorAll(".wildlife-guide-card").forEach(c=>c.addEventListener("click",()=>openGuide(c.dataset.slug)))}
function openGuide(slug){const g=guides.find(x=>x.slug===slug);if(!g)return;const img=relatedImage(g),hero=$("#guideDetailHero");hero.style.backgroundImage=img?`url('${img}')`:"linear-gradient(135deg,#073466,#048da1)";$("#guideDetailCategory").textContent=g.category;$("#guideDetailTitle").textContent=g.title;$("#guideDetailScientific").textContent=g.scientific||"";$("#guideDetailScientific").style.display=g.scientific?"block":"none";$("#guideDetailSummary").textContent=g.summary;$("#guideIdentification").textContent=g.identification;$("#guideHabitat").textContent=g.habitat;$("#guideDiet").textContent=g.diet;$("#guidePhotography").textContent=g.photography;$("#guideFact").textContent=g.fact;const modal=$("#guideModal");modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("no-scroll");history.replaceState(null,"",`#${g.slug}`)}
function closeGuide(){const modal=$("#guideModal");modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.classList.remove("no-scroll");history.replaceState(null,"",location.pathname)}
$("#guideSearch").addEventListener("input",renderGuides);$("#guideModalClose").addEventListener("click",closeGuide);$("#guideModal").addEventListener("click",e=>{if(e.target.id==="guideModal")closeGuide()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeGuide()});
Promise.all([fetch("data/guides.json").then(r=>r.json()),fetch("data/gallery.json").then(r=>r.json()).catch(()=>[])]).then(([g,ga])=>{guides=g;gallery=Array.isArray(ga)?ga:(ga.items||[]);renderFilters();renderGuides();if(location.hash)openGuide(location.hash.slice(1))}).catch(()=>{$("#guideGrid").innerHTML='<p class="empty-state">The guide library could not be loaded.</p>'});